// DOM selectors goes here
const buttonA = document.getElementById("button-a")
const buttonB = document.getElementById("button-b")
const buttonC = document.getElementById("button-c")
const buttonD = document.getElementById("button-d")
const buttonE = document.getElementById("button-e")
const buttonF = document.getElementById("button-f")
const buttonG = document.getElementById("button-g")
const buttonH = document.getElementById("button-h")
const buttonI = document.getElementById("button-i")
const buttonJ = document.getElementById("button-j")
const buttonK = document.getElementById("button-k")
const buttonL = document.getElementById("button-l")
const buttonM = document.getElementById("button-m")
const buttonN = document.getElementById("button-n")
const buttonO = document.getElementById("button-o")
const buttonP = document.getElementById("button-p")
const buttonQ = document.getElementById("button-q")

const blink = (element) => {
  element.classList.add("bright")
  setTimeout(() => element.classList.remove("bright"), 500)
  setTimeout(() => element.classList.add("bright"), 800)
  setTimeout(() => element.classList.remove("bright"), 1300)
}


buttonA.addEventListener("click", () => blink(buttonA))
buttonB.addEventListener("click", () => blink(buttonB))
buttonC.addEventListener("click", () => blink(buttonC))
buttonD.addEventListener("click", () => blink(buttonD))
buttonE.addEventListener("click", () => blink(buttonE))
buttonF.addEventListener("click", () => blink(buttonF))
buttonG.addEventListener("click", () => blink(buttonG))
buttonH.addEventListener("click", () => blink(buttonH))
buttonI.addEventListener("click", () => blink(buttonI))
buttonJ.addEventListener("click", () => blink(buttonJ))
buttonK.addEventListener("click", () => blink(buttonK))
buttonL.addEventListener("click", () => blink(buttonL))
buttonM.addEventListener("click", () => blink(buttonM))
buttonN.addEventListener("click", () => blink(buttonN))
buttonO.addEventListener("click", () => blink(buttonO))
buttonP.addEventListener("click", () => blink(buttonP))
buttonQ.addEventListener("click", () => blink(buttonQ))
